Repository Magic-Fishes/Ecole-Directe-Plus, pull requests merged in 2024-11, with the labels that each got.

#44 Added the documents section
  src/App.css
  src/App.jsx
  src/components/app/Account/Account.css
  src/components/app/Account/Account.jsx
  src/components/app/Grades/Charts.jsx
  src/components/app/Grades/Grade.jsx
  src/components/app/Grades/Information.jsx
  src/components/app/Grades/MobileResults.jsx
  src/components/app/Grades/Strengths.jsx
  src/components/app/Header/Header.css
  src/components/app/Homeworks/Calendar.css
  src/components/app/Homeworks/Calendar.jsx
  src/components/app/Homeworks/Homeworks.jsx
  src/components/app/Messaging/Inbox.jsx
  src/components/app/Messaging/MessageReader.css
  src/components/app/Messaging/MessageReader.jsx
  src/components/app/Messaging/Messaging.css
  src/components/app/Messaging/Messaging.jsx
  src/components/generic/CustomDivs/ScrollShadedDiv.css
  src/components/generic/CustomDivs/ScrollShadedDiv.jsx
  src/components/generic/FileComponent.css
  src/components/generic/PopUps/Tooltip.jsx
  src/components/generic/UserInputs/TextInput.jsx
  src/components/generic/Window.jsx
  src/components/graphics/ArchiveIcon.jsx
  src/components/graphics/DeleteIcon.jsx
  src/components/graphics/DraftIcon.jsx
  src/components/graphics/EditIcon.jsx
  src/components/graphics/InboxIcon.jsx
  src/components/graphics/NewFolderIcon.jsx
  src/components/graphics/PrintIcon.jsx
  src/components/graphics/RenameIcon.jsx
  src/components/graphics/SendIcon.jsx
  src/data/grades.json
  src/utils/iframeRequest/iframeRequestLinker.js
  src/utils/utils.js
Labels: enhancement, type:visual, size:XL

#55 Ajouts des Incidents dans comportement
  src/App.jsx
  src/components/app/Account/Account.css
  src/components/app/Account/Account.jsx
Labels: enhancement, size:XS, area:account

#58 Update vite.config.js
  vite.config.js
Labels: refactoring, development, type:code-quality
